#!/bin/sh
set -e

should_check_main=0

while read local_ref local_sha remote_ref remote_sha

do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    should_check_main=1
    break
  fi
done

if [ "$should_check_main" -ne 1 ]; then
  exit 0
fi

echo "Running Olympus build before pushing to main..."
npm run build
